### ISSUE TITLE
Agregar plugin para validar Apple

### ISSUE THREAD

**Issue by sebastiancesar** [CeiboIT/gamobile-validator#1]
Agregar el plugin https://github.com/pcrawfor/iap_verifier e identificar que datos hay que pedir al owner de la cuenta de apple para poder configurar el validador

**Comment by sebastiancesar** [comment]
Según dice el plugin:

When instantiating the verifier you need to provide the itunes shared secret for the application you are verifying receipts for. This can be found on the itunes connect page for the applications' in app purchases.

Entonces, lo que hace falta es un "itunes shared secret", que vendría siendo el equilvalente al billing_key en android.

**Comment by Epotignano** [comment]
Ok! estos monos lo tienen por aca! ya te lo paso! que manera de laburarle
amigo!

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

2015-11-30 22:27 GMT-03:00 Sebastian Fondra <notifications@github.com>:

**Comment by Epotignano** [comment]
Ya pedi permisos para entrar a la cuenta de apple store, en cuanto los
tenga los paso acá

Potignano Emiliano - CeiboIT

web: www.ceiboit.com
Linkedin: https://ar.linkedin.com/pub/emiliano-potignano/76/242/192
Github: https://github.com/Epotignano
phone: +54 221 525 5778
address: 11 num 2175 b/510 & 511, La Plata, Buenos Aires, Argentina.

2015-11-30 22:30 GMT-03:00 Emiliano Potignano <epotignano@gmail.com>:

**Comment by sebastiancesar** [comment]
Perfecto, esto está en el branch feature/apple

**Comment by sebastiancesar** [comment]
Agregado el shared-secret. Para poder probar este flujo, primero tengo que probar una build en un dispositivo ios. Cierro esto hasta llegar a esa instancia.
